// <auto-generated />
using Boligprospektet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boligprospektet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191212204438_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Boligprospektet.Models.Models_Bolig.Bolig", b =>
                {
                    b.Property<int>("Bolig_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adresse_Code")
                        .HasColumnType("int");

                    b.Property<string>("Adresse_Postnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adresse_Vej")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Annonse_Til")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Antal_Værelser")
                        .HasColumnType("int");

                    b.Property<int>("Areal_msquare")
                        .HasColumnType("int");

                    b.Property<string>("Bolig_Beskrivelser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolig_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Deposit_kr")
                        .HasColumnType("int");

                    b.Property<string>("Ledig_Fra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Leje_kr")
                        .HasColumnType("int");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Bolig_Id");

                    b.ToTable("Boligs");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_Bolig_activitet.Bolig_activitet", b =>
                {
                    b.Property<int>("Bolig_activitet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bolig_Id")
                        .HasColumnType("int");

                    b.Property<string>("Bolig_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolig_activitet_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Bolig_activitet_Id");

                    b.ToTable("Bolig_activitets");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_Bolig_type.Bolig_type", b =>
                {
                    b.Property<int>("Bolig_type_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bolig_type_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Bolig_type_Id");

                    b.ToTable("Bolig_types");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_Bolig_type_activitet.Bolig_type_activitet", b =>
                {
                    b.Property<int>("Bolig_type_activitet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bolig_type_Id")
                        .HasColumnType("int");

                    b.Property<string>("Bolig_type_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bolig_type_activitet_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Bolig_type_activitet_Id");

                    b.ToTable("Bolig_type_activitets");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_Facilitet.Facilitet", b =>
                {
                    b.Property<int>("Facilitet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bolig_Id")
                        .HasColumnType("int");

                    b.Property<string>("Facilitet_Beskrivelser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faciliteter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Facilitet_Id");

                    b.ToTable("Facilitets");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_Indhold.Indhold", b =>
                {
                    b.Property<int>("Indhold_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indhold_Beskrivelser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indhold_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Indhold_Id");

                    b.ToTable("Indholds");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_Indhold_activitet.Indhold_activitet", b =>
                {
                    b.Property<int>("Indhold_activitet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Indhold_Id")
                        .HasColumnType("int");

                    b.Property<string>("Indhold_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indhold_activitet_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Indhold_activitet_Id");

                    b.ToTable("Indhold_activitets");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_User.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuldnavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobile")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Boligprospektet.Models.Models_User_activitet.User_activitet", b =>
                {
                    b.Property<int>("User_activitet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuldnavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_activitet_Navn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_activitet_Id");

                    b.ToTable("User_activitets");
                });
#pragma warning restore 612, 618
        }
    }
}
